### ISSUE TITLE
No semi-colon after case with body

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#26]
From the RFC:

```php
enum Suit implements Colorful {
  case Hearts {
    public function color(): string {
      return "Red";
    }
  };  // Note the semi-colon here!
}
```

I think there should be no semi-colon here. This way we're consistent with methods with or with no body.

```php
abstract class Foo {
    function bar();
    function baz() {}; // Syntax error, unexpected token ";"
}
```

https://3v4l.org/Y0Fe1

Thoughts?

**Comment by Crell** [comment]
I'm fine with it.  My concern is that the syntax then becomes 

`case Foo;`
or
`case Foo { ... }`

So you end up with a semi-colon OR a closing brace.  That feels inconsistent, and I don't know if there are parser implications.  But I don't feel strongly either way.

**Comment by iluuu1994** [comment]
@Crell I just feel like that would be more consistent with existing language constructs.

```php
if ($x);
if ($x) {}

while ($x);
while ($x) {}

function foo();
function foo() {}
```

etc.

**Comment by Crell** [comment]
Fair.  I'll update that once the primitive PR is merged.  Want to do that for now at least as a discussion point, or is there more to adjust for now?

**Comment by iluuu1994** [comment]
Feel free to merge the PR and I'll adjust that afterwards.
