### ISSUE TITLE
Static methods

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#27]
The RFC says:

>  Specifically, the following features of objects are not allowed on enumerations:  Static methods

Any specific reason this shouldn't be allowed? Also, are we talking about enums or the enum cases?

Example where this would be useful:

```php
enum Foo {
    ...

    public static function fromRepresentation1($value) {
        return match ($value) { ... };
    }

    public static function fromRepresentation2($value) {
        return match ($value) { ... };
    }
}

$foo = Foo::fromRepresentation1(1);
$foo = Foo::fromRepresentation2('foo');
```

**Comment by Crell** [comment]
I had intended for both, because I couldn't think of a use case for them.  But that's a good one.  Should we allow static methods on both, or just on the Enum?

**Comment by iluuu1994** [comment]
> Should we allow static methods on both, or just on the Enum?

I'd say just on enums, there's no obvious way to invoke them on enum cases (other than through the instance in which case they could just be an instance method in the first place).

**Comment by Crell** [comment]
Added that, and an example of using a "named constructor" for an enum to demonstrate it.

**Comment by iluuu1994** [comment]
Thank you :)
