### ISSUE TITLE
Reflection

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#28]
The enum currently proposes two new reflection types: `ReflectionEnum` and `ReflectionCase`.

There's a very very large overlap with `ReflectionClass` for both of these since they are in fact just classes. Thus I suggest also actually making them subclasses of `ReflectionClass`.

* `ReflectionEnum::[hasCase|getCases|getCase]`
    * These are in fact practically equivalent to `hasConstant|getConstants|getConstant`
    * Thus, I'm not sure we need/want them
* `ReflectionCase::getEnum`
    * This is exactly equivalent to `getParentClass()`

Note that interfaces and traits also don't have separate reflection classes since they are so similar to classes. I propose doing the same here.

**Comment by Crell** [comment]
As subclasses, then you'd just hard code empty/null returns for the irrelevant class methods, like static methods, properties, and the like?  Or are you suggesting not having separate reflection class at all?

**Comment by iluuu1994** [comment]
> As subclasses, then you'd just hard code empty/null returns for the irrelevant class methods, like static methods, properties, and the like?

Yeah, this will work pretty much out of the box since enums are in fact just classes.

>  Or are you suggesting not having separate reflection class at all?

I think a separate sub-class could make could make sense but we have avoided that in the past. I'm not sure if there's a reason for it.

**Comment by Crell** [comment]
I think Enums are sufficiently non-classy in a user's mind (if not implementation) to give them a separate class, but I'm OK with making them subclasses internally.  I'll update the RFC.

**Comment by iluuu1994** [comment]
Thanks!
