### ISSUE TITLE
Empty enum

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#29]
The RFC currently says:

>  An Enumeration may have one or more case definitions, with no maximum, although at least one is required. 

Any reason for requiring at least one case? All other language constructs allow empty bodies.

**Comment by Crell** [comment]
What use would an empty enum have?  I can't think of one.  A single-element Enum would be a category theory "unit" (a type with only one value, and thus adds no value to a product type), but I don't know what purpose a 0-element Enum has.

**Comment by iluuu1994** [comment]
Nothing really. What's an empty if statement useful for? Nothing really. We allow it anyway :)

**Comment by Crell** [comment]
I don't feel strongly enough about it either way, so whatever gets it the most votes works for me.

**Comment by iluuu1994** [comment]
I think it would be more consistent. We allow empty classes, functions, if statements, switch statements, match expressions, etc.

**Comment by Crell** [comment]
Changed the RFC.

**Comment by iluuu1994** [comment]
Thanks!
