### ISSUE TITLE
Protected is not identical to private

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#30]
>  Public, private, and protected methods. (Protected methods are effectively identical to private as inheritance is not allowed.)

This is true only for enum cases but not the enums themselves.

```php
enum Foo {
    case Bar {
        public function baz() {
            $this->qux(); // Error
        }
    }

    private function qux() {}
}
```

**Comment by Crell** [comment]
Makes sense. I updated the RFC accordingly.

**Comment by iluuu1994** [comment]
Thanks :+1:
