### ISSUE TITLE
Enums as keys

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#32]
This should be added to future scope.

**Comment by Crell** [comment]
Is there a need beyond what WeakMap covers?

**Comment by iluuu1994** [comment]
Yeah for sure. Weak maps memory management is different (if you only track the objects in the map they'll be deallocated) and it can't be serialized.

**Comment by Crell** [comment]
Eh, not convinced, but added to future scope to keep others from asking the same question. :smile:

**Comment by iluuu1994** [comment]
Cool :+1:
