### ISSUE TITLE
Do we need Enum::Case type?

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#33]
> $a instanceof Suit::Spades; // true

I'm not entirely sure we really need support for the *type* `Enum::Case` at this point because it's equivalent to `===`. It's only potentially useful when you want to call methods in some other context without checking/asserting the case first.

**Comment by Crell** [comment]
Possibly not.  I listed that mainly because I expected it would fall out anyway, and to demonstrate that it's a subclass.  Does it not "just work"?

**Comment by iluuu1994** [comment]
Not completely automatic but probably easy. I feel like this part could be a tiny bit controversial. We can also leave it in and I'll see how easy it is to implement.

**Comment by iluuu1994** [comment]
This is irrelevant now.
