### ISSUE TITLE
Allow implementing interfaces in enum cases

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#34]
> Enum Cases may not implement interfaces themselves.

Since we allow implementing methods that are only available in a subset of the cases allowing to implement interfaces only for a subset of cases would probably also make sense.

**Comment by Crell** [comment]
Not a hill I'll die on either way.  Mainly I'm just trying to balance "make enums as powerful as possible" without becoming "there's really no reason to not just use objects". :smile:

**Comment by dbalabka** [comment]
@iluuu1994, @Crell then I would propose to implement abstract methods to be available for Enum class as well. It might give a possibility to easy control methods implementation for each case w/o introducing new interface:
```php
enum SomeEnum {

    case FirstCase {
        public function color() {}
    }

    case SecondCase {
        public function color() {}
    }

    abstract public function color();
}
```

**Comment by iluuu1994** [comment]
This is now irrelevant.
