### ISSUE TITLE
Float to string in cases() assoc array

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#37]
> If the enumeration has a primitive equivalent, the keys will be the corresponding primitive for each enumeration. If the enumeration is of type float, the keys will be rendered as strings. (So a primitive equivalent of 1.5 will result in a key of “1.5”.) 

I'm afraid this could result in some rounding errors.

https://3v4l.org/ng9vE

**Comment by Crell** [comment]
No more or less than floats as array keys, which also get read as strings.  This is the same logic used there.  What should be done with floats otherwise?

**Comment by iluuu1994** [comment]
Not sure... Do we floats anyway is probably what I'm thinking.

**Comment by Crell** [comment]
"Do we floats anyway" - E_PARSE.

**Comment by iluuu1994** [comment]
Lol. I'm really good at "refactoring" sentences until they make no sense whatsoever.

**Comment by iluuu1994** [comment]
Are you ok with removing floats? IMO this is an edge case that is better handled with explicit conversion methods.

**Comment by Crell** [comment]
I don't feel strongly about them. I can't think of a use case off hand but that doesn't mean someone else won't have one.  OTOH, fro what I can tell only Swift and Scala support float enum values. Python is int or string, Rust is int or struct, I am not sure about Kotlin.

So, I'd be OK with losing floats as long as we don't get too much pushback.

**Comment by iluuu1994** [comment]
Ok. Let's remove them for now. It will always be easier to add them in the future than to remove them in case we face issues.

**Comment by Crell** [comment]
RFC updated
