### ISSUE TITLE
enum_exists?

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#38]
https://github.com/php/php-src/pull/6489#issuecomment-739237321

We have `interfaces_exists` and `trait_exists`, do we need `enum_exists` to check whether a given class is an enum?

**Comment by Crell** [comment]
I have no strong opinion at the moment.  On the reflection-related side, I am mostly comfortable with whatever the consensus is.

It probably makes sense, although Dave's point about also wanting symbol_exists() is valid, if tangential.

**Comment by iluuu1994** [comment]
We have the `Enum` interface now so I think this is unnecessary. `class_exists` will return `true`.
