### ISSUE TITLE
should __get be allowed on enum cases ?

### ISSUE THREAD

**Issue by stof** [Crell/enum-comparison#39]
The RFC currently lists `__get` as an allowed method (but not `__set`). given that properties are forbidden, what is the reason to allow magic properties ?

**Comment by Crell** [comment]
```php
enum Suit {
  case Hearts {
    public function __get($param) {
        return match($param) {
            'color' => 'Red',
        };
    }
  }
}
```

Which would allow you to do `Suit::Hearts->color` instead of `Suit::Hearts->color()`.

It's technically nothing that you could also do with methods, but provides a property-like syntax for it if desired.

**Comment by stof** [comment]
but why allowing `Suit::Hearts->color` through magic methods but not through normal properties ?

**Comment by Crell** [comment]
Normal properties would be mutable state.  __get() is not.  However, we've since ended up removing __get anyway for other reasons.  They may get introduced in the future.  (See the future-scope section.)

Closing this for now.
