### ISSUE TITLE
Interaction with the object typehint

### ISSUE THREAD

**Issue by stof** [Crell/enum-comparison#40]
How do enum interact with the `object` typehint ? Being backed by objects, a naive implementation would probably allow enums to satisfy such a typehint. But that might be counter-intuitive for devs not knowing the internal implementation.

**Comment by iluuu1994** [comment]
It's not explicitly written down but generally we would like to make enums as "unspecial" as possible. So IMO yes, `is_object` and the `object` typehint will accept enums.

**Comment by Crell** [comment]
I've updated the RFC to clarify that "what objects do" is the default behavior.
