### ISSUE TITLE
the type of enums and gettype() and is_enum()

### ISSUE THREAD

**Issue by tuqqu** [Crell/enum-comparison#41]
What is Enums type? So far it is not said that Enums introduce a new type, so are they expected to be of type `object`? 

If that's the case does it means that `gettype()` function's output would be `object` and there won't be a corresponding `is_enum()` function, but rather we should use the` is_object()` instead?

Don't you think it would be a little odd not to be able to distinguish between an object and enum value?

**Comment by Crell** [comment]
Enums are, under the hood, objects.  So they'll pass object type hints, etc.  Things like `is_enum()` we're still working on exactly what's appropriate.  Literally, we're discussing that as I'm typing this. :smiley:

**Comment by Crell** [comment]
I've updated the RFC to clarify "what objects do" is the default behavior.
