### ISSUE TITLE
Add internal interfaces for the different types of enum

### ISSUE THREAD

**Issue by Crell** [Crell/enum-comparison#43]
```
interface Enum
interface UnitEnum extends Enum  { public function cases() }
interface ScalarEnum extends Enum { public function value(), public static function from() }
interface TaggedEnum extends Enum
```

**Comment by Crell** [comment]
RFC has been updated accordingly.  @iluuu1994, mark this closed when it's been implemented.

**Comment by iluuu1994** [comment]
According to Nikita my parser workaround for allowing `Enum` is not sufficient. I think we should drop the `Enum` interface for now. It is redundant as we now have `is_enum`.

**Comment by Crell** [comment]
I think I already removed the Enum interface from the RFC itself.

**Comment by iluuu1994** [comment]
It's still under "New interfaces"

**Comment by Crell** [comment]
Removed.

**Comment by iluuu1994** [comment]
Thanks :slightly_smiling_face:
