### ISSUE TITLE
Do we really need case specific methods?

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#45]
Sorry to raise this issue ^^ This has been the main criticism I've heard consistent across all platforms. As you know I have some mixed feeling on them. The benefits I can think of:

1. Exhaustiveness safety at compile time **when** using abstract methods (or interfaces) on the base class

```php
enum Suits {
	public function color();

	case Hearts {
		public function color() {}
	}

	case Diamonds; // Not handled, error
}

```

2. It makes the state machine example possible

While I think the state machine example is cool it's clearly an edge case that can be achieved with a normal class hierarchy.

Do you have any other benefits to add?

**Comment by Crell** [comment]
In some cases it makes the logic cleaner.  If you have a method that does something other than just return a value, it is difficult to fit into a match().  In that case you end up with a match() that branches out to other internal methods, at which point it would be cleaner and less typing to just have discrete case-specific methods.

Remember that methods can have parameters, even if they have no state, so they could be arbitrarily complex.

**Comment by Crell** [comment]
Someone on [Twitter earlier](https://twitter.com/fn_schubert/status/1335534935562743808) offered another good use case for enums: HTTP methods.

I suspect we'll see more use cases crop up, many of which will benefit from methods.  And once we add tagged unions, Those very easily have case-specific methods.

**Comment by iluuu1994** [comment]
>  If you have a method that does something other than just return a value, it is difficult to fit into a match()

You can always move that code into a separate function. With both solutions, we have some kind of repetition.

```php
// Repeated method signatures
enum Suits {
    case Hearts {
        public function color(): string {
            return 'Red';
        }
    }
    case Diamonds {
        public function color(): string {
            return 'Red';
        }
    }
    case Clubs {
        public function color(): string {
            return 'Black';
        }
    }
    case Spades {
        public function color(): string {
            return 'Black';
        }
    }
}

// Repeated enum cases
enum Suits {
    case Hearts;
    case Diamonds;
    case Clubs;
    case Spades;

    public function color(): string {
        return match ($this) {
            self::Hearts, self::Diamonds => 'Red',
            self::Clubs, self::Spades => 'Black',
        };
    }
}
```

So, the longer the method signatures (as in the more params) the more repetition there will be in the first approach.

> Remember that methods can have parameters, even if they have no state, so they could be arbitrarily complex.

I think that's part of the concern. Traditionally, all cases have the exact same API from the outside. That doesn't necessarily discredit it. I do however think there are not enough advantages to support it.

> Someone on Twitter earlier offered another good use case for enums: HTTP methods.

But nothing is different in this example. The same can be achieved with a match with less code.

If you really want different behavior per case you could achieve the same with tagged unions and more specific classes (which would also probably encourage better separation of concerns. Here's an example of something that Rust also does:

```php
class Ipv4 {
    public function doSomething() {}
}

class Ipv6 {
    public function doSomethingElse() {}
}

enum Ip {
    case Ipv4(Ipv4 $ip);
    case Ipv6(Ipv6 $ip);
}
```

The upside here is, we don't need special `Ip::Ipv4` syntax for type hinting, and you can use these types independently without the enum.

@muglug You expressed some concerns. Is there anything specific or is it more just a gut feeling?

**Comment by muglug** [comment]
>  Is there anything specific or is it more just a gut feeling?

It's mostly a gut feeling.

High on my list of useful properties of an enum: you can see, at a glance, all the various values they can hold.

This serves that purpose admirably:

```
enum Suits {
    case Hearts;
    case Diamonds;
    case Clubs;
    case Spades;

    public function color(): string {
        ....
    }
}
````

Allowing methods on the cases, on the other hand, means that you might have to scroll quite some way to see all the cases (supposing each case has multiple methods).

I also generally prefer a language be opinionated about the right way to do a given thing. That also makes my life a bit easier when maintaining Psalm :)

**Edit** 

I also think there's an additional maintenance burden when debugging methods given in the RFC:

If I see a weird value here:

```
foreach (UserStatus::cases() as $key => $val) {
  printf('<option value="%s">%s</option>\n', $key, $val->label());
}
```

I have to look at each case's method in turn, whereas if there's a single method with `match` it makes my life much easier.

**Comment by bwoebi** [comment]
It really depends on the scope. For unitary cases (i.e. non ADT), most methods won't be complex, and a trivial match on a method of the enum class will be easier to read.

Also, it makes sense to _not_ specify some methods on some ADT enums later on. (e.g. the trivial Optional: Optional::Some has a get() function, Optional::None doesn't. Which can be used by code inference analysis to determine that get() may or may not be safely called.)

So, we should have both, both cases are covering issues of different complexity.

I do however think, that for a non-ADT enum RFC, we may move that to future scope, to be included in a RFC including ADTs.

**Comment by iluuu1994** [comment]
> Optional::Some has a get() function, Optional::None doesn't

**Comment by iluuu1994** [comment]
> Optional::Some has a get() function, Optional::None doesn't

Usually there's a method on both, but `None` will throw.

```php
enum Optional {
    case None;
    case Some($value);

    public function unwrap(): mixed {
        if ($this === self::None) {
            throw new Exception();
        }
        return $this->value;
    }
}
```

Or there are variations where a closure is only called if the value is available or whatnot.

**Comment by bwoebi** [comment]
That's _usually_ the case, _because_ you do not have flexible typing and the compiler would like to have a word with you if you tried that in java (without ugly explicit casts).

**Comment by iluuu1994** [comment]
> because you do not have flexible typing

Not sure, I'd argue a "Unwrapped optional was empty" is better than "Unknown method "value()" called on Optional". I realized there might be other cases that are more useful. But as you say, if we do find a good use for them for ADTs we can luckily always add them at a later point in time.

**Comment by muglug** [comment]
Going all-in on the `Optional` type might be a losing battle when PHP already has a widely-understood concept of nullability.

**Comment by bwoebi** [comment]
@muglug It was just the next best example I could grab. Not that I'd really advocate using Optional in PHP :-)
