### ISSUE TITLE
var_export()

### ISSUE THREAD

**Issue by Crell** [Crell/enum-comparison#47]
Right now, it produces a `__set_state`-based output that populates a class.  That's almost certainly wrong.

Instead, probably just produce the FQCN of the case so that = works correctly.

**Comment by iluuu1994** [comment]
Good point. I'm not super-familiar with `var_export` but I'll look into it. We might just auto-implement `__set_state` and return the given constant. **Edit** Or probably better yet just drop the `__set_state` call.

**Comment by iluuu1994** [comment]
This is now handled correctly.
