### ISSUE TITLE
"enum class" keyword?

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#50]
This compound keyword would eliminate the BC break of adding a new keyword. Although it looks a bit less pretty.

```php
enum class Foo {
    case Bar;
}
```

At least something we should consider / talk about.

**Comment by Crell** [comment]
If we have to, I'll deal, but I'd prefer not to.  That seems like it would only encourage more "but why can't I do $some_class_thing with enums? This is stupid" commentary for the next 40 years.

**Comment by iluuu1994** [comment]
I'd also prefer not to. Let's leave it for now. Some people will not be happy about the BC break but it was also kind of expected.

**Comment by iluuu1994** [comment]
C++ and Kotlin are two languages I could find that also use `enum class`. I don't really care either way. Unless somebody strongly objects let's keep it the way it is for now.
