### ISSUE TITLE
Allow constants

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#51]
It has been mentioned multiple times that allowing constants in enums would be useful for creating aliases to avoid BC breaks.

```php
enum Foo {
    case Bar;
    #[Deprecated]
    const Baz = self::Bar;
}
```

**Comment by Crell** [comment]
If this is easy enough to do, I can't think of a reason not to.

Would this allow constants that are a combination of other enums?  I'm thinking of the bitmask type cases.

**Comment by iluuu1994** [comment]
> Would this allow constants that are a combination of other enums? I'm thinking of the bitmask type cases.

I don't understand. You can't do `const BAR_OR_BAZ = self::Bar|self::Baz`. We'll need an `EnumSet` class for bitmask type functionality.
