### ISSUE TITLE
value or value() or getValue()?

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#53]
That is the question.

**Comment by Crell** [comment]
My preference:

* value()
* value
*
*
*
*
*
* getValue()

The `get` prefix is absolutely useless here, and the more I learn about coding practices generally the more convinced I am that get/set prefixes generally are an anti-pattern.

**Comment by iluuu1994** [comment]
> The `get` prefix is absolutely useless here

Well, I don't disagree but that argument could be made anywhere. Internal classes pretty much always use `get` for getters.

**Comment by iluuu1994** [comment]
Implemented as a readonly property for now. @Crell Are you ok with that? Can you adjust the RFC?

**Comment by Crell** [comment]
Already done based on the latest code.
