### ISSUE TITLE
Constant expressions for primitive values?

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#56]
Do we need:

```php
enum Foo: int {
    case A = CONST_A;
    case B = CONST_B;
}
```

@bwoebi FYI

**Comment by Crell** [comment]
I'd consider this a nice-to-have, but not a show stopper.  I don't know how practical or common it would be in practice.

**Comment by iluuu1994** [comment]
Ok, can you specify in the RFC that this is currently not possible? Then we'll see if somebody objects :slightly_smiling_face:

**Comment by Crell** [comment]
Updated.
