### ISSUE TITLE
Rename ScalarEnum to Raw- or ValueEnum?

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#57]
Based on the discussion in R11.

Scalar IMO is not a very descriptive name. 1. Not all scalars are allowed 2. If we ever allow non-scalars (like enums) then the term will also be wrong.

Since our property is called `value` `ValueEnum` might make sense although I think that will become confusing as soon as we have ADTs. I'd prefer `RawEnum` (also renaming `value` to `raw`).

@Crell WDYT?

**Comment by Crell** [comment]
I'm not wedded to "Scalar" Enum as a name if we can find something better.  I don't think it's bad, though.

ValueEnum I agree is tempting, but could also be confusing.

"Raw" implies some unfiltered, unprocessed, potentially dangerous thing.  That's not the case here.  The primitives backing an enum case are not unfiltered, unprocessed, and hopefully not dangerous.  I'm -1 on that.

Is there terminology we can steal from another language?

**Comment by iluuu1994** [comment]
Another option is `BackedEnum`/`value`. I'm not aware of different terms in other languages but I'll do some research.

**Comment by TysonAndre** [comment]
`ReflectionEnumCase::getScalar` could also be renamed to `getValue`, even if the name of ScalarEnum doesn't change. 

I can't think of any good names, just thinking of ideas. SingleValueEnum or ConstantValueEnum?

- Maybe the case without a value could be AnonymousEnum, and cases with a value could just be Enum, and nothing would directly implement Enum
- SingleValueEnum or ConstantValueEnum?
- If `Distance::miles(10)` was ever supported, what would that be called? ParameterizedEnum? Maybe UnparameterizedEnum for those with a value(`case Hearts = 'H';`) and no params, and AnonymousEnum for those with no value.

**Comment by Crell** [comment]
At the moment, the planned names are `UnitEnum`, `ScalarEnum`, and `TaggedEnum`.  None are set in stone, but that's what the RFCs say for now.

**Comment by iluuu1994** [comment]
TaggedUnion, no? The term comes from combining enums (tags) with unions.

**Comment by Crell** [comment]
The ADT RFC right now refers to "Tagged Cases", such that an ADT can include mix of Unit Cases and Tagged Cases, but not Scalar Cases.  As of the moment that is as much as it specifies.

It's not implemented yet so everything there is subject to change if needed.

**Comment by iluuu1994** [comment]
The only other idea I've had was `ConvertibeEnum` which is probably the most explicit. But imo none of the options are great. Any other ideas?

**Comment by iluuu1994** [comment]
Last chance :smile:

* `ScalarEnum`
* `ValueEnum`
* `BackedEnum`

Place your votes. Mine goes to `ValueEnum`.
