### ISSUE TITLE
Swift Optional enum

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#6]
> It also becomes a natural and easy way to implement Monads in user space, and both Haskell and Rust do exactly that in their core libraries. (I'm not clear if Swift does, but you can absolutely do so yourself).

[Swifts `Optional` type is also just an enum](https://developer.apple.com/documentation/swift/optional).

```swift
@frozen enum Optional<Wrapped> 
```

They just have fancy syntax that means the same thing (e.g. `Int?` => `Optional<Int>`).

**Comment by Crell** [comment]
Will update, thanks.
