### ISSUE TITLE
Is the name ReflectionEnumCase(implementation) or ReflectionCase(RFC document) 

### ISSUE THREAD

**Issue by TysonAndre** [Crell/enum-comparison#61]
I don't feel strongly about this - I don't think anything else would be a case that could be reflected on in the future

**Comment by Crell** [comment]
I also don't feel that strongly about it.  I guess ReflectionEnumCase is the more future-proof option.  @iluuu1994?

**Comment by iluuu1994** [comment]
I intentionally picked `ReflectionEnumCase` and forgot to tell you :slightly_smiling_face:

**Comment by Crell** [comment]
Well humph.

RFC updated.
