### ISSUE TITLE
ReflectionEnumConst for ADT compatibility

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#62]
It might be better to make `ReflectionEnumConst` and interface and rename `ReflectionEnumConst` to `ReflectionUnitEnumCase`. This way, when we add ADTs we can create a `ReflectionTaggedUnionCase` (or what have you) that will be based on `ReflectionMethod` (or maybe completely separate).

**Comment by Crell** [comment]
RFC has been updated.  Leaving this open for implementation.  Close when implemented.

**Comment by iluuu1994** [comment]
I actually think we should completely drop `ReflectionEnumCase` until we actually add ADTs. Otherwise it's just an empty interface. Using that in the reflection methods would be completely useless as then you'd just have to assert that it's a unit case.

**Comment by iluuu1994** [comment]
Adjusted in the RFC and implemented.
