### ISSUE TITLE
from/has scalar in reflection

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#63]
From reflection it's currently not possible to get a case from a scalar. Reflection should probably be able to do that.

**Comment by bwoebi** [comment]
technically you can do `$reflectionEnum->getMethod("has")->invoke(null, $someValue);` … And practically `$reflectionEnum->getName()::has($value);`

**Comment by iluuu1994** [comment]
@bwoebi Sure, but is that generally considered enough? Many things in PHP can be done without reflection (`$foo->{$bar}`) but they are generally also possible through reflection.

**Comment by bwoebi** [comment]
I don't care :-D I never use the reflection way unless I have access permission issues (which cannot happen here).

**Comment by Crell** [comment]
Honestly, I'm fine with these not being accessible through reflection directly.  If you're in a reflection context you can always get from there to the actual case object and then call the appropriate methods.  I'm also fine if Ilija wants to add it.  I don't care much either way.

**Comment by iluuu1994** [comment]
Well, let's leave it then :laughing:
