### ISSUE TITLE
Handle failure in from

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#64]
Some people have suggested either

1. Adding a `has` method to know if `from` will succeed
2. Make `from` return `null` instead

I'm not super happy with either of those but we'll probably have to settle for one of them. @Crell Which do you prefer?

/cc @bwoebi

**Comment by bwoebi** [comment]
I wouldn't do `2.` - often enough your inputs come from a trusted source, it's good to have a hard failure there instead of passing null around.

Adding `has` is fine.

**Comment by iluuu1994** [comment]
@Crell I'm ok with option 1 if you are.

**Comment by Crell** [comment]
I'd favor 1.  Forcing the user to check for null every time to avoid random nulls elsewhere is a bad idea.

has-and-exception it is.

**Comment by iluuu1994** [comment]
Not yet specified in the RFC. @Crell Can you do that?

**Comment by Crell** [comment]
Added `has()`.

Should we throw a more specific error for a missing case than just `ValueError`?  Something more easily catchable, like `EnumCaseNotFoundError`, which includes the bad value that was requested?

**Comment by bwoebi** [comment]
I feel like `ValueError` is appropriate - don't catch, use `has()` would be my philosophy. Better for the ecosystem if there are not multiple _obvious_ ways to do the same thing.

**Comment by iluuu1994** [comment]
I think `ValueError` works fine, since that is the only exception thrown by this functions. Thanks!
