### ISSUE TITLE
Override getDeclaringClass() to return ReflectionEnum instead of getEnum()

### ISSUE THREAD

**Issue by iluuu1994** [Crell/enum-comparison#65]
I'm thinking about ways to make reflection simpler. This is one such thing. Instead of adding a redundant `ReflectionEnumCase::getEnum()` method we could simply override `ReflectionClassConst::getDeclaringClass()` and return a `ReflectionEnum` instance instead.

**Comment by Crell** [comment]
So...  You'd end up with this?

```php
$r = new ReflectionEnumCase(Suit::Hearts);
$re = $r->getDeclaringClass();
$re instanceof ReflectionEnum; // true

$r2 = new ReflectionEnumCase(Suit::ConstThatReferencesHearts)->getDeclaringClass();
$r2 instanceof ReflectionEnum; // false
$r2 instanceof ReflectionClass; // true
```

I suppose that's Liskov safe, but still feels a little odd.  The code seems less self-documenting to me.

**Comment by bwoebi** [comment]
$r2 would be still ReflectionEnum, as it's operating on the value. (and not the source of the const)

**Comment by iluuu1994** [comment]
What @bwoebi said :slightly_smiling_face: If you tried `new ReflectionEnumCase(Suit::class, 'ConstThatReferencesHearts')` then yes, that should fail.

**Comment by Crell** [comment]
Is there anything to do here?  Ilija?

**Comment by iluuu1994** [comment]
I just tried it and php was giving me some trouble. Let's forget about it ^^
