### ISSUE TITLE
Java enums do support constructors with parameters

### ISSUE THREAD

**Issue by jurchiks** [Crell/enum-comparison#7]
This comparison survey states: `Enums do not support constructors. (Or rather, the constructor is private, so you cannot pass parameters to it.)`

Official documentation disagrees: https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html
Scroll down to `public enum Planet`, there is a constructor with parameters, which, naturally, can be overloaded.

This is a huge oversight.

**Comment by Crell** [comment]
Hm.  Looks like I misread the other tutorial I was reading.

I have corrected it.  Thanks.

**Comment by jurchiks** [comment]
You missed the Summary table.
