### ISSUE TITLE
I created an online WebAssembly demo for enums 

### ISSUE THREAD

**Issue by TysonAndre** [Crell/enum-comparison#70]
This may help in answering questions reviewers may have about the implementation, or in clarifying answers/misconceptions - https://tysonandre.github.io/php-rfc-demo/enums/

- You can create links with snippets to evaluate - https://tysonandre.github.io/php-rfc-demo/enums/?code=%3C%3Fphp%0A%0Aenum+Suit+%7B%0A++++case+Hearts%3B%0A++++case+Diamonds%3B%0A%7D%0A%0A%24h+%3D+Suit%3A%3AHearts%3B%0A%24h-%3EdynamicPropertyThrows+%3D+123%3B%0A

(the enums rfc has a lot of functionality, and actually being able to run it (without the obstacle of needing to fetch it and compile it from source) may help reviewers understand it or discover edge cases.)

![Screenshot_2021-01-23_09-46-30](https://user-images.githubusercontent.com/1904430/105590085-f5ad8c80-5d5f-11eb-8323-6937a9ab9b80.png)

----

This was an idea I had for a while for my own RFCs; You're the ones working on that RFC and no RFCs I remember even include a demo, so feel free to just not use it or fork it with better examples.

Feel free to close this; this seemed like a better place to post it than current discussion on the php-src PR or mailing list

**Comment by iluuu1994** [comment]
This is really cool, thanks @TysonAndre! I asked Sjön to add to add a branch to https://3v4l.org. He briefly added it but for some reason it vanished. This seems to serve the same purpose. @Crell IMO it would be pretty nice to share this on the ML so people can play around and see if they discover anything that might be surprising to them.

**Comment by iluuu1994** [comment]
We shared it in the ML. Thanks again!
