### ISSUE TITLE
Some feedback on Reddit

### ISSUE THREAD

**Issue by tigitz** [Crell/enum-comparison#73]
Hello,

Just to inform you I took the liberty of posting your repo on reddit, you can see feedback here:

https://www.reddit.com/r/programming/comments/lpdmgt/a_survey_of_programming_language_enum_support/

Thanks a lot for your work on PHP Enum!

**Comment by iluuu1994** [comment]
Thanks for letting us know. Either way, the RFC was already accepted: https://wiki.php.net/rfc/enumerations
